services:
  websharr:
    build:
      context: .

    container_name: websharr
    restart: unless-stopped

    user: "${PUID:-1000}:${PGID:-1000}"

    ports:
      - "9797:9797"

    environment:
      WEBSHARE_USERNAME: ${WEBSHARE_USERNAME:-}
      WEBSHARE_PASSWORD: ${WEBSHARE_PASSWORD:-}
      WEBSHARR_API_KEY: ${WEBSHARR_API_KEY:-}
      TMDB_TOKEN: ${TMDB_TOKEN:-}
      NOTIFY_URLS: ${NOTIFY_URLS:-}

      TZ: ${TZ:-Europe/Bratislava}

      COMPLETE_DIR: /data/websharr/complete
      INCOMPLETE_DIR: /data/websharr/incomplete
      MAX_CONCURRENT_DOWNLOADS: "2"

    volumes:
      - /home/sultan/radarrs/websharr:/config
      - /home/sultan/plex/data:/data

    networks:
      - default

networks:
  default:
    external: true
    name: radarr_default
